### ISSUE TITLE
[request] README.md 파일 작성해 주세요.

### ISSUE THREAD

**Issue by hyunsung-kim** [gpwls320/Project#1]
README.md파일 작성 해 주세요.

**Comment by gpwls320** [comment]
@hyunsung-kim README에 또 뭘 적어야할지 모르겠습니다..ㅠㅠ

**Comment by hyunsung-kim** [comment]
잘 작성하셨습니다. 추가적으로 아래의 내용들이 있으면 좋겠다고 생각해서 남겨 둡니다.
설명 -> 해당 프로젝트의 차별점을 부각해서 적어주면 좋을거 같습니다.
기능 -> 이미 채워 둔거 같더라구요.
참여자 -> 개인 메일을 남겨두시면 됩니다.
