### ISSUE TITLE
[task] Beautifulsoup find/select 질문

### ISSUE THREAD

**Issue by gpwls320** [gpwls320/Project#13]
@hyunsung-kim 튜터님!
app.py 161라인 아까 수업시간에 질문드린 부분이에요ㅠㅠ  도와주세요!

**Comment by hyunsung-kim** [comment]
아래 처럼 적용해 보시고 디버깅하시는 방법 익히시면 좋을 거 같아요. 

가령, soup.select('.price_wrap  .sale  em') 입력해 보시면 "[]" 리스트 표현이 나오는 것을 확인할 수 있습니다. 

이때 [0]으로 가져오시면 됩니다.

```
 brdName = soup.select('.h_group > .brand')[0].text
 prdName = soup.select('.h_group > .product')[0].text
 prdPrice = soup.select('.price_wrap  .sale  em')[0].text
 likePrd_url = soup.select('#img_01')[0]['src']
```

**Comment by hyunsung-kim** [comment]
리스트로 되어 있는 것들이 바로 가져와 지지 않아서 발생하는 문제네요.. 확인해 보시고 위 처럼 바로 개별적으로 가져오시면 될 거 같습니다.

**Comment by gpwls320** [comment]
오 이제 잘 가져오네요!  정말정말 감사합니다 👍👍
