### ISSUE TITLE
[질문] ajax 로딩 이미지 

### ISSUE THREAD

**Issue by gpwls320** [gpwls320/Project#14]
@hyunsung-kim 튜터님..
search.js 21-27라인에 ajax가 실행될 때, ajaxStart, ajaxStop 로 로딩이미지를 노출 시키려고 적용했는데
이미지도 불러오질 못하고ㅠ ajax 실행될 때 아예 먹히질 않는 것 같아요ㅠㅠ

**Comment by hyunsung-kim** [comment]
1. 우선 layout 파일에서 static 파일을 읽어 오려면 아래처럼 사용하시면 됩니다.
```
    <!-- <script src="/static/js/search.js"></script> -->
        <script src="{{ url_for('static', filename='/js/search.js') }}"></script>
```
2.  로딩 파트 수정 - z-index추가
```
  <div id="wrap-loading" style="z-index: 10000;">
            <img src="/static/image/5.gif" alt="Loading..." style="border:0; position:absolute; left:50%; top:50%;" />
        </div>
```

3.  로딩 이미지 위치
<img width="272" alt="스크린샷 2020-04-26 오후 8 26 51" src="https://user-images.githubusercontent.com/57425485/80306208-c97ad480-87fc-11ea-8f46-2baad163f2da.png">

**Comment by hyunsung-kim** [comment]
완전 변경된 UI이네요.. 좋습니다.
로딩 부분은 원하실 때 하셔야 할거 같아요. 전체로 적용하면 뭔가 어색할 수 있습니다. 확인하셔서 잘 사용하세요.

**Comment by gpwls320** [comment]
오! 감사합니다 👍👍
