### ISSUE TITLE
[질문] 크롤링할 쇼핑몰 설정 관련 질문.

### ISSUE THREAD

**Issue by gpwls320** [gpwls320/Project#6]
@hyunsung-kim 
쇼핑몰 솔루션마다 검색 결과를 불러오는 화면 구성이 달라서 특정 쇼핑몰(카페24면 카페24, 고도몰이면 고모돌)로 제한해서 쇼핑몰로 등록하거나 특정 사이트(w컨셉, 무신사 등)로 미리 설정해서 해야할 것 같은데 어떻게 하는게 좋을지 모르겠습니다..;_;

**Comment by hyunsung-kim** [comment]
이 경우에는 하나씩 하는 방법 말고도 특별히 방법이 없는거 같아요. 가장 쉬운 사이트 부터 시작하시죠.

**Comment by gpwls320** [comment]
@hyunsung-kim 넵! 감사합니다🙂
