### ISSUE TITLE
[질문] pymongo ssesion 시간 수정 문의

### ISSUE THREAD

**Issue by gpwls320** [gpwls320/Project#8]
@hyunsung-kim
https://github.com/hyunsung-kim/flask-pymongo-session
src/app.py에서 ssesion 시간을 늘리고 싶은데 어디를 수정해야할지 모르겠습니다.. T_T

**Comment by hyunsung-kim** [comment]
42줄이 시간을 의미합니다. 이걸 증가 시키려면  expiration = datetime.utcnow() +  timedelta(hours=1)
아래 처럼 하시면 50일입니다.
```
 delta = timedelta(
...     days=50
... )
```

**Comment by gpwls320** [comment]
@hyunsung-kim 오오 감사합니다:D
